
cc_library(
    name = "helpers",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    deps = [
        "//third_party/wpilibsuite:wpilib",
        "//third_party/ctre:ctre",
        "//lib/filters:filters",
        "//lib/util:util",
        "//lib/managers:managers",
        "//lib/logging:logging",
    ],
    visibility = ["//visibility:public"],
)
