
cc_library(
    name = "info",
    srcs = glob([
    ]),
    hdrs = glob([
        "RobotInfo.h",
    ]),
    deps = [
        "//third_party/wpilibsuite:wpilib",
        "//third_party/ctre:ctre",
    ],
    visibility = ["//visibility:public"],
)
