sudo: required

language: cpp

services:
  - docker

before_install:
 - docker build -t team973/frc-bazel .

script:
 - docker run team973/frc-bazel /bin/sh -c "bazel build //src:robot --cpu=roborio"
 - docker run team973/frc-bazel /bin/sh -c "bazel test //tools/pathtool:test --verbose_failures"

notifications:
  slack: greybotsfrc973:dwVtOBBSTIHn2Th9zIUGfpCX
