
cc_library(
    name = "pixelprocessors",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    deps = [
      "//lib/util:util",
    ],
    visibility = ["//visibility:public"],
)
