
cc_library(
    name = "sensors",
    srcs = glob([
        "*.cpp",
    ]),
    hdrs = glob([
        "*.h",
    ]),
    deps = [
        "//lib/util:util",
        "//third_party/wpilibsuite:wpilib",
        "//third_party/ctre:ctre",
    ],
    visibility = ["//visibility:public"],
)
