filegroup(
    name = "doxygen_build",
    srcs = ["doxygen.sh"],
    visibility = ["//visibility:public"],
)

filegroup(
  name = "doxyfile",
  srcs = ["Doxyfile.in"],
  visibility = ["//visibility:public"],
)
